config/routes.rb
Taskmanager::Application.routes.draw do
  
  devise_for :users

  root :to => 'progects#index'
  resources :progects do
    resources :tasks
  end

  
  
  

end

app/models/progect.rb
class Progect < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  belongs_to :user
  attr_accessible :name
  validates :name, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :progect
  attr_accessible :name, :progect_id, :status
  validates :name, :progect_id, :status, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :progects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/progects_controller.rb
class ProgectsController < ApplicationController
  
  before_filter :authenticate_user!

  # GET /progects
  # GET /progects.json
  def index
    #binding.pry
    #@progects = Progect.find_by_user_id(current_user.id)
    @progects = Progect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @progects }
    end
  end

  # GET /progects/1
  # GET /progects/1.json
  def show
    @progect = Progect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @progect }
    end
  end

  # GET /progects/new
  # GET /progects/new.json
  def new
    @progect = Progect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @progect }
    end
  end

  # GET /progects/1/edit
  def edit
    @progect = Progect.find(params[:id])
  end

  # POST /progects
  # POST /progects.json
  def create
    @progect = Progect.new(params[:progect])
    @progect.user_id = current_user.id

    respond_to do |format|
      if @progect.save
        format.html { redirect_to @progect, :notice => 'Progect was successfully created.' }
        format.json { render :json => @progect, :status => :created, :location => @progect }
      else
        format.html { render :action => "new" }
        format.json { render :json => @progect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /progects/1
  # PUT /progects/1.json
  def update
    @progect = Progect.find(params[:id])

    respond_to do |format|
      if @progect.update_attributes(params[:progect])
        format.html { redirect_to @progect, :notice => 'Progect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @progect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /progects/1
  # DELETE /progects/1.json
  def destroy
    @progect = Progect.find(params[:id])
    @progect.destroy

    respond_to do |format|
      format.html { redirect_to progects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def task
  end
  
  def create
    @progect = Progect.find(params[:progect_id])
    @task = @progect.tasks.create(params[:task])
    redirect_to progect_path(@progect)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/progects_helper.rb
module ProgectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskmanager</title>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id = "user_nav">
  <% if user_signed_in? %>

    Signed in as <%= current_user.email %>. Not you ?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>

    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>

  <% end %>
</div>	

<% flash.each do |name, msg| %>

  <%= content_tag :div, msg, :id => "flash_#{name}" %>

<% end %>


<%= yield %>

</body>
</html>

app/views/progects/_form.html.erb
<%= form_for(@progect) do |f| %>
  <% if @progect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@progect.errors.count, "error") %> prohibited this progect from being saved:</h2>

      <ul>
      <% @progect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progects/_task.html.erb
               <tr>
                <td></td>
                <td></td>                
                <td><%= "-- Task № #{t.id}: #{t.name}" %></td>
                <td><%= t.status %></td>
                <td></td> 
                <td></td> 
                <td></td>                                                 
                <td></td>                  
              </tr>  

app/views/progects/edit.html.erb
<h1>Editing progect</h1>

<%= render 'form' %>

<%= link_to 'Show', @progect %> |
<%= link_to 'Back', progects_path %>

app/views/progects/index.html.erb
<h1>Simple TODO List</h1>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th></th>
    <th>Progect_Id</th>
    <th>Name</th>
    <th>Status</th>    
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>

  </tr>

    <% @progects.each do |progect| %>
      <% if progect.user_id == current_user.id %>
      <tr>
        <th><i class="icon-plus"></i></th>
        
        <td><%= progect.id %></td>
        <td><%= progect.name %></td>
        <td></td>
        <td></td>        
        <td><%= link_to "Show #{progect.id} progect", progect %></td>
        <td><%= link_to "Edit #{progect.id} progect", edit_progect_path(progect) %></td>
        <td><%= link_to "Destroy #{progect.id} progect", progect, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>

      </tr>

            <% progect.tasks.each do |t| %>
     
                 <%= render partial: 'task', locals: { t: t } %>

             <% end %>
      <% end %>
    <% end %>

</table>

<br />

<%= link_to 'New Progect', new_progect_path %>

app/views/progects/new.html.erb
<h1>New progect</h1>

<%= render 'form' %>

<%= link_to 'Back', progects_path %>

app/views/progects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3>Progect name:</h3>
  <%= @progect.name %>
</p>

  <h3> Tasks:</h3>
        <% @progect.tasks.each do |t| %>
             <%= render partial: 'task', locals: { t: t } %>
         <% end %>

  <h3> Add task </h3>
   
 <%= form_for ([@progect, @progect.tasks.build]) do |f| %>  
  <p>
     <%= f.label :task %> </br>
   <%= f.text_field :name %>
  </p>
  
    <p>
   <%= f.label :status %> </br>
   <%= f.text_field :status %>
  </p>
  
  <p>
  	<%= f.submit %>
  </p>
  
 <% end %>


<%= link_to 'Edit', edit_progect_path(@progect) %> |
<%= link_to 'Back', progects_path %>

app/views/tasks/task.html.erb
<h1>Tasks#task</h1>
<p>Find me in app/views/tasks/task.html.erb</p>